[tool.poetry]
name = "day-4"
version = "0.1.0"
description = ""
authors = ["tmeanor <tmeanor@starbucks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
